"""Explicit validation contracts (GAPS decisions 12-13): per-flow
bpt/ept pairing and ``i`` uniqueness, and the cross-variant ``x`` advisory.

The pairing oracle is independent of the implementation's walk: valid
structures are generated by a purpose-built generator that maintains one
``i`` counter per flow it constructs (shared through ``<hi>``, fresh for
``<sub>``), and every structural mutation of a valid tree (dropping an
``ept``, renumbering one, duplicating a ``bpt``) must be rejected.
"""

import itertools
import random
import warnings
from collections.abc import Callable, Iterator
from typing import Any

import pytest
from pydantic import ValidationError

from hypomnema.errors import TmxDeprecationWarning, TmxWarning
from hypomnema.models import (
  Bpt,
  Ept,
  Header,
  Hi,
  It,
  Map,
  Note,
  Ph,
  Property,
  Sub,
  TranslationUnit,
  TranslationUnitVariant,
  Ude,
  Ut,
)
from hypomnema.validation import (
  validate,
  validate_header,
  validate_translation_unit,
  validate_translation_unit_variant,
  validate_ude,
)


def tuv(*content: Any, xml_lang: str = "en") -> TranslationUnitVariant:
  return TranslationUnitVariant(xml_lang=xml_lang, content=content)


def unit(*variants: TranslationUnitVariant) -> TranslationUnit:
  return TranslationUnit(variants=variants)


def full_header(metadata: tuple[Note | Property | Ude, ...]) -> Header:
  return Header(
    creationtool="CT",
    creationtoolversion="1",
    segtype="block",
    o_tmf="G",
    adminlang="en",
    srclang="en",
    datatype="txt",
    metadata=metadata,
  )


def expect_pairing_error(fn: Callable[[], None], *message_bits: str) -> ValidationError:
  with pytest.raises(ValidationError) as excinfo:
    fn()
  error = excinfo.value.errors()[0]
  assert error["type"] == "inline_tag_pairing"
  for bit in message_bits:
    assert bit in error["msg"]
  return excinfo.value


# Acceptance: legal per decision 12, including the shapes a stack-nesting
# check would get wrong.


# Advisories (GAPS decisions 8/15/19): models are silent; the validation
# pass is the one place they fire.


def test_legacy_lang_without_xml_lang_warns_in_the_tu_pass() -> None:
  tu = TranslationUnit(variants=(tuv("x"),), metadata=(Note(lang="fr"),))
  with pytest.warns(TmxDeprecationWarning, match="prefer xml:lang"):
    validate_translation_unit(tu)


def test_differing_lang_values_warn_in_the_tu_pass() -> None:
  tu = TranslationUnit(variants=(tuv("x"),), metadata=(Note(lang="fr", xml_lang="de"),))
  with pytest.warns(TmxWarning, match="differ"):
    validate_translation_unit(tu)


def test_legacy_lang_warns_in_the_variant_pass() -> None:
  variant = TranslationUnitVariant(xml_lang="en", metadata=(Property(type="t", lang="fr"),), content=("x",))
  with pytest.warns(TmxDeprecationWarning, match="prefer xml:lang"):
    validate_translation_unit_variant(variant)


def test_variant_own_lang_differs_and_warns() -> None:
  # Only the differing case is reachable on a variant: xml_lang is required,
  # so legacy lang alone is a typing error, not an advisory.
  with pytest.warns(TmxWarning, match="differ"):
    validate_translation_unit_variant(TranslationUnitVariant(xml_lang="en", lang="fr"))


def test_variant_own_lang_equal_ignoring_case_is_silent() -> None:
  with warnings.catch_warnings():
    warnings.simplefilter("error")
    validate_translation_unit_variant(TranslationUnitVariant(xml_lang="EN-us", lang="en-US"))


def test_deprecated_ut_warns_in_the_content_walk() -> None:
  with pytest.warns(TmxDeprecationWarning, match="deprecated"):
    validate_translation_unit_variant(tuv(Ut()))


def test_map_without_target_warns_in_validate_ude() -> None:
  ude = Ude(name="u", maps=(Map(unicode=0xF8FF),))
  with pytest.warns(TmxWarning, match="at least one of"):
    validate_ude(ude)


def test_map_with_any_target_is_silent_in_validate_ude() -> None:
  ude = Ude(name="u", maps=(Map(unicode=0xF8FF, ent="x"),))
  with warnings.catch_warnings():
    warnings.simplefilter("error")
    validate_ude(ude)


def test_header_metadata_advisories_fire_in_validate_header() -> None:
  header = full_header((Note(lang="fr"), Ude(name="u", base="ascii", maps=(Map(unicode=0x41, ent="A"),))))
  with pytest.warns(TmxDeprecationWarning, match="prefer xml:lang"):
    validate_header(header)


# The Ude base/code rule (GAPS decisions 6/19): pure validate_ude, one error
# per offending map, located under the metadata position by the header pass.


def test_ude_base_required_when_a_map_carries_code() -> None:
  with pytest.raises(ValidationError) as excinfo:
    validate_ude(Ude(name="u", maps=(Map(unicode=0x41, code=0x42),)))
  error = excinfo.value.errors()[0]
  assert error["type"] == "ude_base_required"
  assert error["loc"] == (0,)


def test_ude_reports_every_offending_map() -> None:
  ude = Ude(name="u", maps=(Map(unicode=0x41), Map(unicode=0x42, code=0x43), Map(unicode=0x44, code=0x45)))
  with pytest.raises(ValidationError) as excinfo:
    validate_ude(ude)
  assert [error["loc"] for error in excinfo.value.errors()] == [(1,), (2,)]


def test_ude_with_base_is_accepted() -> None:
  with warnings.catch_warnings():
    warnings.simplefilter("error")
    validate_ude(Ude(name="u", base="ascii", maps=(Map(unicode=0x41, code=0x42),)))


def test_validate_header_prefixes_ude_error_locations() -> None:
  header = full_header((Ude(name="u", maps=(Map(unicode=0x41, code=0x42),)),))
  with pytest.raises(ValidationError) as excinfo:
    validate_header(header)
  assert excinfo.value.errors()[0]["loc"] == ("metadata", 0, 0)


def test_validate_header_aggregates_across_udes() -> None:
  header = full_header(
    (Ude(name="a", maps=(Map(unicode=0x41, code=0x42),)), Ude(name="b", maps=(Map(unicode=0x41, code=0x43),)))
  )
  with pytest.raises(ValidationError) as excinfo:
    validate_header(header)
  assert [error["loc"] for error in excinfo.value.errors()] == [("metadata", 0, 0), ("metadata", 1, 0)]


# The validate(node) dispatcher (GAPS decision 19): fragment-level flows.


def test_standalone_sub_flow_is_checked() -> None:
  with pytest.raises(ValidationError) as excinfo:
    validate(Sub(content=("x", Bpt(i=1), "y")))
  assert excinfo.value.errors()[0]["type"] == "inline_tag_pairing"


def test_standalone_hi_flow_is_checked() -> None:
  with pytest.raises(ValidationError):
    validate(Hi(content=(Ept(i=1),)))


def test_paired_tag_fragment_checks_its_sub_flows() -> None:
  with pytest.raises(ValidationError):
    validate(Bpt(i=1, content=(Sub(content=(Bpt(i=2),)),)))


def test_placeholder_tag_fragment_checks_its_sub_flows() -> None:
  with pytest.raises(ValidationError):
    validate(Ph(content=("t", Sub(content=("s", Ept(i=9))), "end")))


def test_a_fragment_cannot_carry_the_enclosing_flow() -> None:
  # A lone bpt/ept/it/ph has no enclosing flow to pair into, so its own
  # presence is not an error; enclosing-flow checks apply at tuv/tu level.
  validate(Bpt(i=1))
  validate(Ept(i=1))


def test_dispatcher_emits_the_leaf_advisories() -> None:
  with pytest.warns(TmxDeprecationWarning, match="prefer xml:lang"):
    validate(Note(lang="fr"))
  with pytest.warns(TmxWarning, match="at least one of"):
    validate(Map(unicode=0x41))
  with pytest.warns(TmxDeprecationWarning, match="deprecated"):
    validate(Ut())


def test_non_node_is_rejected_loudly() -> None:
  impostor: Any = object()
  with pytest.raises(TypeError, match="not a TMX node model"):
    validate(impostor)


def test_a_simple_pair_is_accepted() -> None:
  validate_translation_unit_variant(tuv("a", Bpt(i=1), "b", Ept(i=1), "c"))


def test_overlapping_pairs_are_legal() -> None:
  # The spec permits overlapping native code pairs; matching is per-i.
  validate_translation_unit_variant(tuv(Bpt(i=1), Bpt(i=2), Ept(i=1), Ept(i=2)))


def test_pairing_inside_hi_joins_the_enclosing_flow() -> None:
  validate_translation_unit_variant(tuv(Bpt(i=1), Hi(content=("x", Bpt(i=2), Ept(i=1))), Ept(i=2)))


def test_sub_is_its_own_flow_and_may_reuse_i() -> None:
  sub_flow = Sub(content=("f", Bpt(i=1), "g", Ept(i=1), "h"))
  validate_translation_unit_variant(tuv(Bpt(i=1), "b", Ept(i=1), It(pos="begin", content=(sub_flow,)), "j"))


def test_pairing_works_deep_inside_sub_and_hi() -> None:
  deep_sub = Sub(content=("s", Hi(content=("h", Bpt(i=9), Ept(i=9))), "t"))
  validate_translation_unit_variant(tuv(Bpt(i=1, content=(deep_sub, "t")), Ept(i=1)))


def test_content_without_inline_tags_is_accepted() -> None:
  validate_translation_unit_variant(tuv("just text"))


def test_a_sub_without_pairing_is_accepted() -> None:
  validate_translation_unit_variant(tuv(Ph(content=(Sub(content=("code",)),))))


def test_the_same_i_on_bpt_and_ept_is_the_pairing_itself() -> None:
  validate_translation_unit_variant(tuv(Bpt(i=1), Ept(i=1)))


def test_all_placeholder_tags_open_sub_flows() -> None:
  sub_pair = (Sub(content=(Bpt(i=1), Ept(i=1))),)
  with warnings.catch_warnings():
    warnings.simplefilter("ignore")  # the ut deprecation advisory is not this test's subject
    # The bpt/ept cases carry their own outer-flow partners.
    validate_translation_unit_variant(tuv("a", Bpt(i=1, content=sub_pair), Ept(i=1), "b"))
    validate_translation_unit_variant(tuv("a", Bpt(i=1), Ept(i=1, content=sub_pair), "b"))
    validate_translation_unit_variant(tuv("a", It(pos="end", content=sub_pair), "b"))
    validate_translation_unit_variant(tuv("a", Ph(content=sub_pair), "b"))
    validate_translation_unit_variant(tuv("a", Ut(content=sub_pair), "b"))


# Rejection: unmatched, orphaned, and duplicated i, with locations.


def test_unmatched_bpt_is_rejected() -> None:
  error = expect_pairing_error(
    lambda: validate_translation_unit_variant(tuv(Bpt(i=1), "text")), "no subsequent corresponding <ept>"
  )
  assert error.errors()[0]["loc"] == ("content", 0)


def test_orphan_ept_is_rejected() -> None:
  error = expect_pairing_error(lambda: validate_translation_unit_variant(tuv("a", Ept(i=1))), "no corresponding <bpt>")
  assert error.errors()[0]["loc"] == ("content", 1)


def test_ept_before_its_bpt_is_rejected_as_orphan() -> None:
  expect_pairing_error(lambda: validate_translation_unit_variant(tuv(Ept(i=1), Bpt(i=1))), "no corresponding <bpt>")


def test_duplicate_bpt_i_is_rejected() -> None:
  error = expect_pairing_error(
    lambda: validate_translation_unit_variant(tuv(Bpt(i=1), Bpt(i=1))), "duplicate <bpt> i=1"
  )
  assert error.errors()[0]["loc"] == ("content", 1)


def test_duplicate_ept_i_is_rejected() -> None:
  error = expect_pairing_error(
    lambda: validate_translation_unit_variant(tuv(Bpt(i=1), Ept(i=1), Ept(i=1))), "duplicate <ept> i=1"
  )
  assert error.errors()[0]["loc"] == ("content", 2)


def test_duplicate_i_inside_a_sub_flow_does_not_spill_into_the_outer_flow() -> None:
  dup_sub = Sub(content=(Bpt(i=1), Bpt(i=1)))
  error = expect_pairing_error(
    lambda: validate_translation_unit_variant(tuv(Bpt(i=1, content=(dup_sub,)))), "duplicate <bpt> i=1"
  )
  # loc reaches into the sub flow: bpt > content[0] > sub > content[1]
  assert error.errors()[0]["loc"] == ("content", 0, "content", 0, "content", 1)


def test_an_ept_in_one_sub_does_not_close_a_bpt_in_the_enclosing_flow() -> None:
  sibling_sub = Sub(content=("a", Ept(i=1)))
  with pytest.raises(ValidationError) as excinfo:
    validate_translation_unit_variant(tuv(Bpt(i=1, content=(sibling_sub,))))
  messages = [error["msg"] for error in excinfo.value.errors()]
  assert len(messages) == 2
  assert any("no corresponding <bpt>" in message for message in messages)  # the sub-flow orphan
  assert any("no subsequent corresponding <ept>" in message for message in messages)  # the outer bpt


def test_errors_aggregate() -> None:
  with pytest.raises(ValidationError) as excinfo:
    validate_translation_unit_variant(tuv(Bpt(i=1), Bpt(i=1), Ept(i=3)))
  assert len(excinfo.value.errors()) == 3


def test_a_valid_flow_inside_an_invalid_variant_is_not_reported() -> None:
  # Only the broken flow produces an error, and its loc points at it.
  broken_sub = Sub(content=("s", Bpt(i=2)))
  good_sub = Sub(content=(Bpt(i=3), Ept(i=3)))
  with pytest.raises(ValidationError) as excinfo:
    validate_translation_unit_variant(tuv(Bpt(i=1, content=(good_sub, broken_sub)), Ept(i=1)))
  assert len(excinfo.value.errors()) == 1
  assert excinfo.value.errors()[0]["loc"] == ("content", 0, "content", 1, "content", 1)


# Translation-unit level: per-variant checks plus the x advisory (decision 13).


def test_variant_errors_carry_the_variant_index() -> None:
  with pytest.raises(ValidationError) as excinfo:
    validate_translation_unit(unit(tuv("a", Bpt(i=1)), tuv("b", Ept(i=1))))
  assert excinfo.value.errors()[0]["loc"] == ("variants", 0, "content", 1)
  assert excinfo.value.errors()[1]["loc"] == ("variants", 1, "content", 1)


def test_a_structural_error_wins_over_the_x_advisory() -> None:
  # A broken unit raises; the advisory does not fire on top of it.
  with pytest.raises(ValidationError):
    validate_translation_unit(unit(tuv("a", Bpt(i=1, x=5)), tuv("b", Ept(i=1))))


def test_matching_x_sets_are_silent() -> None:
  with warnings.catch_warnings():
    warnings.simplefilter("error")
    validate_translation_unit(unit(tuv("a", Bpt(i=1, x=5), Ept(i=1)), tuv("b", Ph(x=5))))


def test_mismatched_x_sets_warn_once_per_unit() -> None:
  tu = unit(tuv("a", Bpt(i=1, x=5), Ept(i=1)), tuv("b", Bpt(i=1, x=6), Ept(i=1)), tuv("c"))
  with pytest.warns(TmxWarning, match="different inline x values") as caught:
    validate_translation_unit(tu)
  assert len(caught) == 1


def test_no_x_values_at_all_is_silent() -> None:
  with warnings.catch_warnings():
    warnings.simplefilter("error")
    validate_translation_unit(unit(tuv("a", Bpt(i=1), Ept(i=1)), tuv("b")))


def test_ut_x_is_excluded_from_the_matching_set() -> None:
  # The spec's x "Used in" list omits <ut>, so its x must not create a
  # mismatch; the deprecation advisory itself is tested in
  # test_deprecated_ut_warns_in_the_content_walk above, and
  # validate_translation_unit emits it as part of the pass (GAPS decision
  # 19), so it is silenced by category -- wording-independent -- while
  # every other TmxWarning, including an x mismatch, stays an error.
  with warnings.catch_warnings():
    warnings.simplefilter("ignore")
    tu = unit(tuv("a", Ut(x=1), Bpt(i=1), Ept(i=1)), tuv("b", Bpt(i=1), Ept(i=1)))
  with warnings.catch_warnings():
    warnings.simplefilter("error")
    warnings.filterwarnings("ignore", category=TmxDeprecationWarning)
    validate_translation_unit(tu)


def test_equal_x_values_across_different_element_kinds_match() -> None:
  # The spec's cross-variant matching is by x value between bpt/it/ph/hi,
  # not by element kind.
  tu = unit(tuv("a", Bpt(i=1, x=1), Ept(i=1)), tuv("b", Ph(x=1)))
  with warnings.catch_warnings():
    warnings.simplefilter("error")
    validate_translation_unit(tu)


def test_a_variant_without_x_values_disagrees_with_one_with_them() -> None:
  tu = unit(tuv("a", Bpt(i=1, x=5), Ept(i=1)), tuv("b", Bpt(i=1), Ept(i=1)))
  with pytest.warns(TmxWarning, match="different inline x values"):
    validate_translation_unit(tu)


def test_x_inside_nested_content_counts() -> None:
  inner_sub = Sub(content=(Hi(x=7),))
  tu = unit(tuv("a", Bpt(i=1, content=(inner_sub,)), Ept(i=1)), tuv("b", Hi(x=7)))
  with warnings.catch_warnings():
    warnings.simplefilter("error")
    validate_translation_unit(tu)


# Cycles (GAPS decision 7a): only mutation can create them. Detection is
# scoped to each walk's root, so legitimately shared subtrees stay legal.


def cyclic_pair() -> tuple[Hi, Hi]:
  outer, inner = Hi(), Hi()
  outer.content = (inner,)
  inner.content = (outer,)
  return outer, inner


def test_two_step_hi_cycle_is_rejected() -> None:
  outer, _ = cyclic_pair()
  with pytest.raises(ValidationError) as excinfo:
    validate_translation_unit_variant(tuv(outer))
  assert excinfo.value.errors()[0]["type"] == "cyclic_content"


def test_cycle_through_sub_is_rejected() -> None:
  sub = Sub(content=())
  bpt = Bpt(i=1, content=(sub,))
  sub.content = (bpt,)
  with pytest.raises(ValidationError) as excinfo:
    validate_translation_unit_variant(tuv(bpt))
  assert excinfo.value.errors()[0]["type"] == "cyclic_content"


def test_cycle_error_points_at_the_reentered_node() -> None:
  outer, _ = cyclic_pair()
  # The re-entry happens when walking outer's content: its first item is
  # inner, whose first content item is outer again. Each descent appends
  # ("content", index, "content"), so the re-entry sits three levels deep.
  with pytest.raises(ValidationError) as excinfo:
    validate_translation_unit_variant(tuv(outer))
  assert excinfo.value.errors()[0]["loc"] == ("content", 0, "content", 0, "content", 0)


def test_cycle_does_not_descend_so_errors_stay_bounded() -> None:
  # The cyclic pair is referenced three times; each re-entry reports once.
  outer, _ = cyclic_pair()
  with pytest.raises(ValidationError) as excinfo:
    validate_translation_unit_variant(tuv(outer, outer, outer))
  assert len(excinfo.value.errors()) == 3


def test_a_shared_subtree_is_legal_across_variants() -> None:
  shared = Hi()
  validate_translation_unit(unit(tuv(Hi(content=("x", shared))), tuv(Hi(content=(shared, "y")))))


def test_a_diamond_is_not_a_cycle() -> None:
  shared = Hi()
  validate_translation_unit_variant(tuv(Hi(content=(shared, shared))))


# Fuzz: independently generated valid trees are accepted; structural
# mutations of valid trees are rejected; nothing escapes ValidationError.


def _random_valid_flow(rng: random.Random, depth: int, counter: Iterator[int]) -> tuple[Any, ...]:
  """Build a tree that satisfies decision 12 by construction: one shared
  ``i`` counter per flow (shared through <hi>, fresh for <sub>)."""
  items: list[Any] = []
  for _ in range(rng.randint(0, 4)):
    kind = rng.random()
    if kind < 0.25 or depth <= 0:
      items.append(f"text{rng.randint(0, 99)}")
    elif kind < 0.45:  # adjacent pair whose bpt carries sub flows
      i = next(counter)
      sub_count = rng.randint(1, 2)
      sub_flows = tuple(Sub(content=_random_valid_flow(rng, depth - 1, itertools.count(1))) for _ in range(sub_count))
      items.append(Bpt(i=i, content=sub_flows))
      items.append(Ept(i=i, content=sub_flows if rng.random() < 0.3 else ()))
    elif kind < 0.65:  # wrapping pair; the wrapped flow shares the namespace
      i = next(counter)
      items.append(Bpt(i=i))
      items.extend(_random_valid_flow(rng, depth - 1, counter))
      items.append(Ept(i=i))
    elif kind < 0.8:  # transparent highlight
      items.append(Hi(content=_random_valid_flow(rng, depth - 1, counter)))
    else:  # placeholder tag carrying its own sub flow
      sub_flow = _random_valid_flow(rng, depth - 1, itertools.count(1))
      if rng.random() < 0.5:
        items.append(It(pos=rng.choice(["begin", "end"]), content=(Sub(content=sub_flow),)))
      elif rng.random() < 0.5:
        items.append(Ph(content=(Sub(content=sub_flow),)))
      else:
        items.append(Ut(content=(Sub(content=sub_flow),)))
  return tuple(items)


def test_fuzz_valid_trees_are_accepted() -> None:
  rng = random.Random(424242)
  with warnings.catch_warnings():
    warnings.simplefilter("ignore")
    for _ in range(300):
      content = _random_valid_flow(rng, depth=3, counter=itertools.count(1))
      validate_translation_unit_variant(TranslationUnitVariant(xml_lang="en", content=as_generated(content)))


def as_generated(content: tuple[Any, ...]) -> Any:
  """A generated list/tuple of models the static checker must not judge."""
  return content


def _random_any_flow(rng: random.Random, depth: int) -> tuple[Any, ...]:
  """Like the valid generator but with independent random i values, so
  duplicates, orphans, and crossings occur naturally."""
  items: list[Any] = []
  for _ in range(rng.randint(0, 4)):
    kind = rng.random()
    if kind < 0.3 or depth <= 0:
      items.append(f"text{rng.randint(0, 99)}")
    elif kind < 0.55:
      i = rng.randint(0, 4)
      sub_count = rng.randint(1, 2)
      sub_flows = tuple(Sub(content=_random_any_flow(rng, depth - 1)) for _ in range(sub_count))
      items.append(Bpt(i=i, content=sub_flows))
      if rng.random() < 0.8:
        items.append(Ept(i=rng.randint(0, 4), content=sub_flows if rng.random() < 0.3 else ()))
    elif kind < 0.7:
      items.extend(_random_any_flow(rng, depth - 1))
    elif kind < 0.85:
      items.append(Hi(content=_random_any_flow(rng, depth - 1)))
    else:
      sub_flow = _random_any_flow(rng, depth - 1)
      if rng.random() < 0.5:
        items.append(It(pos=rng.choice(["begin", "end"]), content=(Sub(content=sub_flow),)))
      else:
        items.append(Ut(content=(Sub(content=sub_flow),)))
  return tuple(items)


def _all_epts(node: Any) -> list[Ept]:
  if isinstance(node, Ept):
    return [node]
  if isinstance(node, str):
    return []
  found: list[Ept] = []
  for child in node.content:
    found.extend(_all_epts(child))
  return found


def test_fuzz_rejections_never_escape_validation_error() -> None:
  rng = random.Random(909)
  with warnings.catch_warnings():
    warnings.simplefilter("ignore")
    for _ in range(500):
      content = _random_any_flow(rng, depth=3)
      try:
        validate_translation_unit_variant(TranslationUnitVariant(xml_lang="en", content=as_generated(content)))
      except ValidationError:
        continue
      # No other exception type may escape; acceptance is covered by the
      # valid-tree and mutation tests.


def test_mutating_a_valid_tree_is_always_rejected() -> None:
  rng = random.Random(31337)
  with warnings.catch_warnings():
    warnings.simplefilter("ignore")
    for _ in range(300):
      content = _random_valid_flow(rng, depth=3, counter=itertools.count(1))
      epts = [node for node in _iter_nodes(content) if isinstance(node, Ept)]
      if not epts:
        continue
      victim = rng.choice(epts)
      mutation = rng.choice(["drop", "renumber", "duplicate_bpt"])
      if mutation == "drop":
        broken = _drop_node(content, victim)
      elif mutation == "renumber":
        victim.i = rng.randint(1000, 2000)  # mutates in place, detaching the pair
        broken = content
      else:
        broken = _insert_after(content, victim, Bpt(i=victim.i))
      with pytest.raises(ValidationError) as excinfo:
        validate_translation_unit_variant(TranslationUnitVariant(xml_lang="en", content=as_generated(broken)))
      assert all(error["type"] == "inline_tag_pairing" for error in excinfo.value.errors())


def _iter_nodes(items: tuple[Any, ...]) -> Iterator[Any]:
  for node in items:
    if isinstance(node, str):
      continue
    yield node
    for child in _iter_nodes(node.content):
      yield child


def _drop_node(items: tuple[Any, ...], victim: Ept) -> tuple[Any, ...]:
  kept: list[Any] = []
  for node in items:
    if node is victim:
      continue
    if isinstance(node, str):
      kept.append(node)
    else:
      kept.append(type(node).model_construct(**{**node.model_dump(), "content": _drop_node(node.content, victim)}))
  return tuple(kept)


def _insert_after(items: tuple[Any, ...], after: Ept, node: Bpt) -> tuple[Any, ...]:
  rebuilt: list[Any] = []
  for item in items:
    if isinstance(item, str):
      rebuilt.append(item)
      continue
    if item is after:
      rebuilt.append(item)
      rebuilt.append(node)
    else:
      rebuilt.append(
        type(item).model_construct(**{**item.model_dump(), "content": _insert_after(item.content, after, node)})
      )
  return tuple(rebuilt)
