"""Base types and errors for Hypomnema.

This module provides the core data structures and exceptions used throughout
the library.
"""

from .errors import (
  XmlAttributeError,
  DeserializationError,
  InvalidChildElementError,
  InvalidChildTagError,
  InvalidEnumValueError,
  InvalidIntValueError,
  InvalidNCNameError,
  InvalidPolicyActionError,
  InvalidTagError,
  MissingDeserializationHandlerError,
  MissingHeaderError,
  MissingSerializationHandlerError,
  MultiplePrefixesError,
  NamespaceError,
  RestrictedPrefixError,
  RestrictedURIError,
  SerializationError,
  UnregisteredPrefixError,
  UnregisteredURIError,
)
from .types import (
  Assoc,
  BaseElement,
  Bpt,
  Ept,
  Header,
  Hi,
  InlineElement,
  It,
  Note,
  Ph,
  Pos,
  Prop,
  Segtype,
  Sub,
  Tmx,
  Tu,
  Tuv,
)

__all__ = [
  "Assoc",
  "XmlAttributeError",
  "BaseElement",
  "Bpt",
  "DeserializationError",
  "Ept",
  "Header",
  "Hi",
  "InlineElement",
  "InvalidChildElementError",
  "InvalidChildTagError",
  "InvalidEnumValueError",
  "InvalidIntValueError",
  "InvalidNCNameError",
  "InvalidPolicyActionError",
  "InvalidTagError",
  "It",
  "MissingDeserializationHandlerError",
  "MissingHeaderError",
  "MissingSerializationHandlerError",
  "MultiplePrefixesError",
  "NamespaceError",
  "Note",
  "Ph",
  "Pos",
  "Prop",
  "RestrictedPrefixError",
  "RestrictedURIError",
  "Segtype",
  "SerializationError",
  "Sub",
  "Tmx",
  "Tu",
  "Tuv",
  "UnregisteredPrefixError",
  "UnregisteredURIError",
]
